title: West Coast Institute
kramdown:
  input: GFM
permalink: pretty
exclude:
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - asserts/lib
  - vendor
  - node_modules
  - _site
collections:
  books:
    output: true
    permalink: /:path/
  chapters:
    output: false
  paragraphs:
    output: false
